DATAROOT = "./data"  # for running in personal computer
# DATAROOT = "/cluster/scratch/zhajin/data/"  # for running in euler cluster

used_characteristics = ['volume', 'ReturnSkew', 'MaxRet', 'delta', 'PriceDelaySlope', 'strike_price', 
                        'IdioVol3F', 'ReturnSkew3F', 'ir_rate', 'mid_price', 'forwardprice', 
                        'zerotradeAlt1', 'theta', 'cfadj', 'zerotrade', 'best_bid', 'spotprice', 'VolMkt', 
                        'IdioRisk', 'days_to_exp', 'PriceDelayTstat', 'High52', 'Coskewness', 'BidAskSpread', 
                        'Beta', 'days_no_trading', 'open_interest', 'impl_volatility', 'PriceDelayRsq', 'IdioVolAHT', 
                        'adj_spot', 'vega', 'gamma', 'best_offer', 'DolVol', 'cp_flag_encoded']

used_characteristics = ['AM', 'AOP', 'AbnormalAccruals', 'Accruals', 'AccrualsBM', 'Activism1', 'Activism2',
                        'AdExp', 'AgeIPO', 'AnalystRevision', 'AnalystValue', 'AnnouncementReturn', 'AssetGrowth', 
                        'BM', 'BMdec', 'BPEBM', 'Beta', 'BetaFP', 'BetaLiquidityPS', 'BetaTailRisk', 'BidAskSpread', 
                        'BookLeverage', 'BrandInvest', 'C', 'CBOperProf', 'CF', 'Cash', 'CashProd', 'ChAssetTurnover', 
                        'ChEQ', 'ChForecastAccrual', 'ChInv', 'ChInvIA', 'ChNAnalyst', 'ChNNCOA', 'ChNWC', 'ChTax', 
                        'ChangeInRecommendation', 'CitationsRD', 'CompEquIss', 'CompositeDebtIssuance', 'ConsRecomm', 
                        'ConvDebt', 'CoskewACX', 'Coskewness', 'CredRatDG', 'CustomerMomentum', 'DebtIssuance', 
                        'DelBreadth', 'DelCOA', 'DelCOL', 'DelDRC', 'DelEqu', 'DelFINL', 'DelLTI', 'DelNetFin', 
                        'DivInit', 'DivOmit', 'DivSeason', 'DivYieldST', 'DolVol', 'DownRecomm', 'EBM', 'EP', 
                        'EarnSupBig', 'EarningsConsistency', 'EarningsForecastDisparity', 'EarningsStreak', 
                        'EarningsSurprise', 'EntMult', 'EquityDuration', 'ExchSwitch', 'ExclExp', 'FEPS', 'FR', 
                        'FirmAge', 'FirmAgeMom', 'ForecastDispersion', 'Frontier', 'GP', 'Governance', 'GrAdExp', 
                        'GrLTNOA', 'GrSaleToGrInv', 'GrSaleToGrOverhead', 'Herf', 'HerfAsset', 'HerfBE', 'High52', 
                        'IO_ShortInterest', 'IdioRisk', 'IdioVol3F', 'IdioVolAHT', 'Illiquidity', 'IndIPO', 'IndMom', 
                        'IndRetBig', 'IntMom', 'IntanBM', 'IntanCFP', 'IntanEP', 'IntanSP', 'InvGrowth', 
                        'InvestPPEInv', 'Investment', 'LRreversal', 'Leverage', 'MRreversal', 'MS', 'MaxRet', 
                        'MeanRankRevGrowth', 'Mom12m', 'Mom12mOffSeason', 'Mom6m', 'Mom6mJunk', 'MomOffSeason', 
                        'MomOffSeason06YrPlus', 'MomOffSeason11YrPlus', 'MomOffSeason16YrPlus', 'MomRev', 'MomSeason', 
                        'MomSeason06YrPlus', 'MomSeason11YrPlus', 'MomSeason16YrPlus', 'MomSeasonShort', 'MomVol', 
                        'NOA', 'NetDebtFinance', 'NetDebtPrice', 'NetEquityFinance', 'NetPayoutYield', 
                        'NumEarnIncrease', 'OPLeverage', 'OScore', 'OperProf', 'OperProfRD', 'OptionVolume1', 
                        'OptionVolume2', 'OrderBacklog', 'OrderBacklogChg', 'OrgCap', 'P', 'PS', 'PatentsRD', 
                        'PayoutYield', 'PctAcc', 'PctTotAcc', 'PredictedFE', 'PriceDelayRsq', 'PriceDelaySlope', 
                        'PriceDelayTstat', 'ProbInformedTrading', 'RD', 'RDAbility', 'RDIPO', 'RDS', 'RDcap', 'REV6', 
                        'RIO_Disp', 'RIO_MB', 'RIO_Turnover', 'RIO_Volatility', 'ResidualMomentum', 'ReturnSkew', 
                        'ReturnSkew3F', 'RevenueSurprise', 'RoE', 'SP', 'ShareIss1Y', 'ShareIss5Y', 'ShareRepurchase', 
                        'ShareVol', 'ShortInterest', 'SmileSlope', 'Spinoff', 'SurpriseRD', 'Tax', 'TotalAccruals', 
                        'UpRecomm', 'VarCF', 'VolMkt', 'VolSD', 'VolumeTrend', 'XFIN', 'betaVIX', 'bucket_dvol', 
                        'bucket_vol', 'bucket_vol_share', 'cfp', 'dNoa', 'dciv', 'delta', 'doi', 'dpiv', 'dso', 
                        'dvol', 'embedlev', 'expiration_month', 'fgr5yrLag', 'gamma', 'grcapx', 'grcapx3y', 
                        'hire', 'iomom_cust', 'iomom_supp', 'iv', 'ivd', 'ivslope', 'ldso', 'lso', 'mid', 
                        'moneyness', 'nopt', 'ntm_civpiv', 'oi', 'oistock', 'optspread', 'pba', 'pcpv', 
                        'pcratio', 'realestate', 'retConglomerate', 'roaq', 'sfe', 'shrtfee', 'sinAlgo', 
                        'skew1', 'skewiv', 'so', 'std_turn', 'tang', 'theta', 'toi', 'ttm', 'turnover', 'vega', 
                        'vol', 'volga', 'vs_change', 'vs_level', 'zerotrade', 'zerotradeAlt1', 'zerotradeAlt12']

used_characteristics = ['AM', 'AOP', 'AbnormalAccruals', 'Accruals', 'AccrualsBM', 'Activism1',
                        'Activism2', 'AdExp', 'AgeIPO', 'AnalystRevision', 'AnalystValue', 'AnnouncementReturn', 'AssetGrowth', 'BM', 'BMdec', 'BPEBM', 'Beta', 'BetaFP', 'BetaLiquidityPS', 'BetaTailRisk', 'BidAskSpread', 'BookLeverage', 'BrandInvest', 'C', 'CBOperProf', 'CF', 'Cash', 'CashProd', 'ChAssetTurnover', 'ChEQ', 'ChForecastAccrual', 'ChInv', 'ChInvIA', 'ChNAnalyst', 'ChNNCOA', 'ChNWC', 'ChTax', 'ChangeInRecommendation', 'CitationsRD', 'CompEquIss', 'CompositeDebtIssuance', 'ConsRecomm', 'ConvDebt', 'CoskewACX', 'Coskewness', 'CredRatDG', 'CustomerMomentum', 'DebtIssuance', 'DelBreadth', 'DelCOA', 'DelCOL', 'DelDRC', 'DelEqu', 'DelFINL', 'DelLTI', 'DelNetFin', 'DivInit', 'DivOmit', 'DivSeason', 'DivYieldST', 'DolVol', 'DownRecomm', 'EBM', 'EP', 'EarnSupBig', 'EarningsConsistency', 'EarningsForecastDisparity', 'EarningsStreak', 'EarningsSurprise', 'EntMult', 'EquityDuration', 'ExchSwitch', 'ExclExp', 'FEPS', 'FR', 'FirmAge', 'FirmAgeMom', 'ForecastDispersion', 'Frontier', 'GP', 'Governance', 'GrAdExp', 'GrLTNOA', 'GrSaleToGrInv', 'GrSaleToGrOverhead', 'Herf', 'HerfAsset', 'HerfBE', 'High52', 'IO_ShortInterest', 'IdioRisk', 'IdioVol3F', 'IdioVolAHT', 'Illiquidity', 'IndIPO', 'IndMom', 'IndRetBig', 'IntMom', 'IntanBM', 'IntanCFP', 'IntanEP', 'IntanSP', 'InvGrowth', 'InvestPPEInv', 'Investment', 'LRreversal', 'Leverage', 'MRreversal', 'MS', 'MaxRet', 'MeanRankRevGrowth', 'Mom12m', 'Mom12mOffSeason', 'Mom6m', 'Mom6mJunk', 'MomOffSeason', 'MomOffSeason06YrPlus', 'MomOffSeason11YrPlus', 'MomOffSeason16YrPlus', 'MomRev', 'MomSeason', 'MomSeason06YrPlus', 'MomSeason11YrPlus', 'MomSeason16YrPlus', 'MomSeasonShort', 'MomVol', 'NOA', 'NetDebtFinance', 'NetDebtPrice', 'NetEquityFinance', 'NetPayoutYield', 'NumEarnIncrease', 'OPLeverage', 'OScore', 'OperProf', 'OperProfRD', 'OptionVolume1', 'OptionVolume2', 'OrderBacklog', 'OrderBacklogChg', 'OrgCap', 'P', 'PS', 'PatentsRD', 'PayoutYield', 'PctAcc', 'PctTotAcc', 'PredictedFE', 'PriceDelayRsq', 'PriceDelaySlope', 'PriceDelayTstat', 'ProbInformedTrading', 'RD', 'RDAbility', 'RDIPO', 'RDS', 'RDcap', 'REV6', 'RIO_Disp', 'RIO_MB', 'RIO_Turnover', 'RIO_Volatility', 'ResidualMomentum', 'ReturnSkew', 'ReturnSkew3F', 'RevenueSurprise', 'RoE', 'SP', 'ShareIss1Y', 'ShareIss5Y', 'ShareRepurchase', 'ShareVol', 'ShortInterest', 'SmileSlope', 'Spinoff', 'SurpriseRD', 'Tax', 'TotalAccruals', 'UpRecomm', 'VarCF', 'VolMkt', 'VolSD', 'VolumeTrend', 'XFIN', 'betaVIX', 'bucket_dvol', 'bucket_vol', 'bucket_vol_share', 'cfp', 'dNoa', 'dciv', 'delta', 'doi', 'dpiv', 'dso', 'dvol', 'embedlev', 'expiration_month', 'fgr5yrLag', 'gamma', 'grcapx', 'grcapx3y', 'hire', 'iomom_cust', 'iomom_supp', 'iv', 'ivd', 'ivslope', 'ldso', 'lso', 'mid', 'moneyness', 'nopt', 'ntm_civpiv', 'oi', 'oistock', 'optspread', 'pba', 'pcpv', 'pcratio', 'realestate', 'retConglomerate', 'roaq', 'sfe', 'shrtfee', 'sinAlgo', 'skew1', 'skewiv', 'so', 'std_turn', 'tang', 'theta', 'toi', 'ttm', 'turnover', 'vega', 'vol', 'volga', 'vs_change', 'vs_level', 'zerotrade', 'zerotradeAlt1', 'zerotradeAlt12',
                        'ind_10', 'ind_12', 'ind_13', 'ind_14', 'ind_15',
                        'ind_16', 'ind_17', 'ind_20', 'ind_21', 'ind_22', 'ind_23', 'ind_24',
                        'ind_25', 'ind_26', 'ind_27', 'ind_28', 'ind_29', 'ind_30', 'ind_31',
                        'ind_32', 'ind_33', 'ind_34', 'ind_35', 'ind_36', 'ind_37', 'ind_38',
                        'ind_39', 'ind_40', 'ind_41', 'ind_42', 'ind_44', 'ind_45', 'ind_46',
                        'ind_47', 'ind_48', 'ind_49', 'ind_50', 'ind_51', 'ind_52', 'ind_53',
                        'ind_54', 'ind_55', 'ind_56', 'ind_57', 'ind_58', 'ind_59', 'ind_60',
                        'ind_61', 'ind_62', 'ind_63', 'ind_64', 'ind_65', 'ind_67', 'ind_70',
                        'ind_72', 'ind_73', 'ind_75', 'ind_76', 'ind_78', 'ind_79', 'ind_80',
                        'ind_82', 'ind_83', 'ind_87', 'ind_89', 'ind_90', 'ind_95', 'ind_97',
                        'ind_99'
                        ]
